openapi: 3.0.1
info:
  title: LS.MFC.Service
  description: LS MFC is used for direct communication with warehouse automation. LS MFC transmits the commands received from WMS for execution to the automation.
  termsOfService: https://logisystem.eu/en/
  contact:
    name: LOGISYSTEM Sp. z o.o.
    url: https://logisystem.eu/en/
    email: office@logisystem.eu;r.lazarz@logisysstem.eu
  version: v1
paths:
  /sorting:
    post:
      tags:
        - ParcelSorting
      summary: ''
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SortingPayload'
          text/json:
            schema:
              $ref: '#/components/schemas/SortingPayload'
          application/*+json:
            schema:
              $ref: '#/components/schemas/SortingPayload'
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ApiResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Bad Request
components:
  schemas:
    APIResponseError:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: integer
          description: Error Code
          format: int32
        message:
          minLength: 1
          type: string
          description: Error message
      additionalProperties: false
    APIResponseStatusEnum:
      enum:
        - success
        - error
      type: string
    ActionEnum:
      enum:
        - insert
        - update
        - delete
      type: string
      description: Action type for parcel item
    ApiResponse:
      required:
        - status
      type: object
      properties:
        status:
          $ref: '#/components/schemas/APIResponseStatusEnum'
        errDetails:
          $ref: '#/components/schemas/APIResponseError'
      additionalProperties: false
      description: ''
    Parcel:
      required:
        - action
        - idCourier
        - idParcel
        - waybillNo
      type: object
      properties:
        idParcel:
          minLength: 1
          type: string
          description: 'Unique identifier for the parcel, from WMS'
        action:
          $ref: '#/components/schemas/ActionEnum'
        idCourier:
          minLength: 1
          type: string
          description: 'The parameter is interchangeable with the idDirection parameter (never both together, always one of them). The message includes the courier''s ID, e.g .: DHL, DPD, INP, UPS... Interpretation by MFC: - If the parameter is present, MFC directs the packet to the appropriate slot on the sorter. The slot [IdDirection] is configured in the MFC for the idCourier'
        idDirection:
          type: string
          description: 'Direction number. The parameter is interchangeable with the idCourier parameter (never both together, always one of them). Interpretation by MFC: - If the parameter is present, the MFC directs the parcel to the appropriate slot on the sorter.'
          nullable: true
        waybillNo:
          minLength: 1
          type: string
          description: 'Waybill Number. This number is printed on the parcel label as a barcode. Based on the code, the automation recognizes the parcel, and directs it to the destination.'
      additionalProperties: false
      description: Sorted parcel
    SortingPayload:
      required:
        - idMessage
        - parcels
      type: object
      properties:
        idMessage:
          minLength: 1
          type: string
          description: 'Request identifier (GUID). Generated by the initiating system. The purpose is: idRequest can be processed once, and for diagnostic purposes.'
        parcels:
          type: array
          items:
            $ref: '#/components/schemas/Parcel'
          description: List of parcels to be sorted.
      additionalProperties: false
      description: Sorted parcel